Drop the 2000ms timeout
With this change, I would expect to start seeing more like:
  1) #query-bar when using advanced query options when using the fanclub collection with 100 docs goes to the index tab and creates an index:
     Error: element (#statusbar) still  visible after 2000ms
https://travis-ci.com/10gen/compass/jobs/71231588