Travis should pass (#988)
* Revert "Dont fire query change store if no collection selected (#981)"

This reverts commit ca2a7bfb6bdc2de40d979dfb6fd1c291d8c08a43.

I don't fully understand this, but it is failing a test both on Travis and locally, shortest way to retest is:
npm test -- --functional -g '#launch|#schema'

Test output:

  7 passing (32s)
  2 pending
  1 failing

  1) #schema when applying a filter in the schema tab shows a schema on refresh:
     AssertionError: expected 'Query returned 0 documents. This report is based on a sample of 1 documents (0.00%).' to include 'Query returned 1 document. This report is based on a sample of 1 document (100.00%).'

npm ERR! Test failed.  See above for more details.

* Resolve deterministic (100% of the time) indexes test timeout

Introduced in #975
https://github.com/10gen/compass/commit/9e21614f114616e8af2f57e31675ec74703ea6e5