[Backport 1.9] COMPASS 1747 Fire onCollectionChanged in more cases (#1227) (#1230)
* :hammer: Refactor NamespaceStore test

* :white_check_mark: Add some basic unit tests

* :white_check_mark: Add test to detect the :bug:

* :bug: onCollectionChange should fire on either of DB or Collection changed

Example: db1.coll => db2.coll, the collection component is identical, but it is a different collection because it is on a different database.

* :bug: Reuse mongodb-ns

It handles the '.' in collection names correctly.

* :art: Use contexts for test readability

* :white_check_mark: Add test to detect the second :bug:

* :bug: Initialize to the default namespace of ''

Reproduced on local with:
npm test -- --functional

https://travis-ci.com/10gen/compass/jobs/88742497

#retry
  1) CollectionsStore "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/89088707