COMPASS 156 Range Component - queryToParams (#546)
* COMPASS 156: DV - range component queryToParams

Revert "Revert "Temporarily add range rule in" so partial progress stays hidden"

This reverts commit cb9a1cc2e8eaeace296397b79cec912c30c1e653.

* Migrate validation.rule.test.js into Compass CI tests

* Move validation.store.test.js into CI tests, skipping errors

I don't understand where these are coming from, so skip them for now as it's unclear if we might want to go back to a separate shareable repo in future:

FIRST ERROR
--------------------
    ✓ goes into {fetchState: "error"} when receiving an error back
TypeError: Cannot set property 'validator' of undefined
    at Store._deconstructValidatorDoc (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:81:7)
    at _fetchFromServer (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:223:27)
    at Timeout._onTimeout (/Users/pzrq/Projects/compass/test/validation.store.test.js:14:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot set property 'validator' of undefined
    at Store._deconstructValidatorDoc (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:81:7)
    at _fetchFromServer (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:223:27)
    at Timeout._onTimeout (/Users/pzrq/Projects/compass/test/validation.store.test.js:14:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    1) goes into {fetchState: "error"} when receiving an invalid validator doc
Failed with exit code: 1

SECOND ERROR
-------------------------
    ✓ goes into {fetchState: "error"} when receiving an error back
    - goes into {fetchState: "error"} when receiving an invalid validator doc
TypeError: Cannot set property 'validator' of undefined
    at Store._deconstructValidatorDoc (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:81:7)
    at _fetchFromServer (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:223:27)
    at Timeout._onTimeout (/Users/pzrq/Projects/compass/test/validation.store.test.js:14:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot set property 'validator' of undefined
    at Store._deconstructValidatorDoc (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:81:7)
    at _fetchFromServer (/Users/pzrq/Projects/compass/src/internal-packages/validation/lib/stores/index.js:223:27)
    at Timeout._onTimeout (/Users/pzrq/Projects/compass/test/validation.store.test.js:14:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    1) goes into {fetchState: "error"} when the result is not an object
{ AssertionError: expected 1 to equal 2
    at Timeout.setTimeout (/Users/pzrq/Projects/compass/test/validation.store.test.js:110:35)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
  message: 'expected 1 to equal 2',
  showDiff: true,
  actual: 1,
  expected: 2 }
AssertionError: expected 1 to equal 2
    at Timeout.setTimeout (/Users/pzrq/Projects/compass/test/validation.store.test.js:110:35)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    2) "after each" hook

* Migrate range code and tests from compass-validation repo

* Refactor logic into validateKeyAndValue

Lowers the complexity of queryToParams from 14 to 12.

* Remove chained if to lower complexity

Fixes TODO.

* Drop infinity support and add some negative and decimals tests

Infinity is dropped as the empty clause is better and so we don't have to represent it in the GUI.

* Improve test context

* Get values from an existing validatorDoc shown in GUI

At a mongo shell:
use validation;
> db.runCommand({collMod: 'validation', validator: {"age": {$gte:0.01,$lt:5000 },     "phone_no": {       "$regex": "^[0-9 ]+$",       "$options": "mx"     }   }});

* Get {<, <=, >, >=, none} server validatorDoc shown in dropdown GUI

At a mongo shell:
use validation;
> db.runCommand({collMod: 'validation', validator: {"age": {$gte:0.01,$lt:5000 },     "phone_no": {       "$regex": "^[0-9 ]+$",       "$options": "mx"     }   }});

* Hide range component again and skip integration tests

Full range component to come in a JIRA linked to COMPASS-156 or COMPASS-235.

* Structure & naming things request from @rueckstiess, thanks!

* Skip things again

Coming in COMPASS-235, definitely working on that today so we can stop this back and forth partial stuff.

* Drop unnecessary skips

* fix “fetching” test, allow callback to be called once

* Fix RangeInput test warnings about missing non-default required "value"

* Drop "are not useful"

Wasn't found in earlier string replace in COMPASS-156