Don't require external actions in store init() (#912)
* use listenToExternalStore instead of listening to action

appRegistry may not be set up yet when the listener is attached. ListenToExternalStore avoids that, and in this case is just as good as listening to setInstance action.

* similar case: action required but appRegistry may not be initialized

* remove all external actions from store inits

* undo CollectionStore dynamic fetch

#retry
  1) Compass Main Functional Test Suite #spectron when a MongoDB instance is running when viewing the database lists the collections in the database:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/70561552

  1) Compass Main Functional Test Suite #spectron when a MongoDB instance is running when connecting to a server when the server exists renders the home screen:
     Error: Promise was rejected with the following reason: timeout
https://travis-ci.com/10gen/compass/jobs/70561550

... creates the document #race
https://travis-ci.com/10gen/compass/jobs/70562703

  1) Compass Main Functional Test Suite #spectron when a MongoDB instance is running "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/70563341

* Add #race to 'deletes upon confirmation'

1) Compass Main Functional Test Suite #spectron when a MongoDB instance is running when viewing a collection when deleting a document deletes upon confirmation:
     Error: An element could not be located on the page using the given search parameters.
https://travis-ci.com/10gen/compass/jobs/70395246
https://travis-ci.com/10gen/compass/jobs/70563989