fix(check): Don't require modules in jade tpls
It makes acorn go bonkers!  And you’ll see a strange error message like:

```
/Users/lucas/scout/node_modules/mongodb-js-precommit/node_modules/depend
ency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:1747
  throw err;
        ^
SyntaxError: Assigning to rvalue (1:0)
```