COMPASS-944: Part1 - Functional charts tests (#934)
* Document how to run a subset of the tests

* Add basic functional test for the Charts Tab

Ideally I'd prefer to handle the nested field 'location.city' by getting the title attributes from the grandchildren of the 'chart-builder-field-panel' component, but I don't know how to, at least yet hence the comments.

* Improve location.city nested field test case

Using QA feedback comments, the base pattern from:
https://github.com/10gen/compass/blob/166426b6763fe6205e3a758d79490d4e73182135/test/functional/support/packages/spectron-explain.js#L80

Plus starting to learn WebDriverIO:
http://webdriver.io/guide/usage/selectors.html

* Resolve style nitpick

Not sure how to turn on:
http://eslint.org/docs/rules/space-before-function-paren

#retry
Travis log has no reason for failure in its output?
https://travis-ci.com/10gen/compass/jobs/72055111

  1) #charts when manipulating documents in the crud view "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/72056573
(Appears to be the same dataService / goToCollection issue seen in https://github.com/10gen/compass/pull/926#issuecomment-292851948 )