npm uninstall ncp --save
'ncp' used to be used for the main process migrations:
https://github.com/10gen/compass/pull/370/files

The last 'ncp' usage appears to have been removed in:
https://github.com/10gen/compass/pull/899/files

#retry
  1) #schema "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/72938472

Also have now cleared all Travis caches to be on the safe side as .travis.yml currently caches node_modules and `npm install` does not uninstall unused dependencies by default.