COMPASS-995 Schema Tab Tooltip (#918)
* Remove existing tooltip

* Add back in a HadronTooltip

* Remove redundant Schema shouldComponentUpdate

It defaults to true:
https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate

* Make Schema tooltips opaque with normal padding

As it is on master, also remove redundant data-effect: solid which is already present in the tooltip (as compared to float where the tooltip floats around as you move the mouse over the tooltip area).

* Test refactor: DRY field and type requires

Note: In this file you can already see enzyme tests with the tooltip data exist in the same pattern as was expected from COMPASS 904:
https://github.com/10gen/compass/pull/904/files#diff-141ece4d9c46a6395999a8d5653c2803

#retry
'#query-bar when using advanced query options when using the fanclub collection with 100 docs goes to the index tab and creates an index'
https://travis-ci.com/10gen/compass/jobs/71072503

  1) #query-bar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71073705

  1) #sidebar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71074834

  1) #connect when connecting to a server when the server exists renders the home screen:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71074835

  1) #launch when launching the application displays the feature tour modal:
     Error: element ([data-test-id='feature-tour-modal']) still not visible after 13000ms
https://travis-ci.com/10gen/compass/jobs/71074831

  1) #explain "before all" hook:
     element (title=MongoDB Compass - localhost:27018) still not existing after 13000ms
https://travis-ci.com/10gen/compass/jobs/71074832

* Only rebuild tooltips if the Schema Tab is active

#retry
  1) #sidebar "before all" hook:
     Error: An element could not be located on the page using the given search parameters ("input[name=hostname]").
https://travis-ci.com/10gen/compass/jobs/71220029

  1) #schema when applying a filter in the schema tab shows a schema on refresh:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) #schema when applying a filter in the schema tab applies the filter from schema view:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  3) #schema when applying a filter in the schema tab checks the collections table:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  4) #schema when applying a filter in the schema tab applies the filter again while on schema tab:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  5) #schema "after all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71220030

  1) #indexes "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) #indexes "after all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  3) #query-bar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  4) #schema "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  5) #sidebar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71220032

  1) #connect when connecting to a server when the server exists renders the home screen:
     Error: element (title=MongoDB Compass - localhost:27018) still not existing after 13000ms
      at elements("title=MongoDB Compass - localhost:27018") - isExisting.js:46:17
      at isExisting("title=MongoDB Compass - localhost:27018") - waitForExist.js:37:22
  2) #connect when connecting to a server when the server exists displays the instance details:
      AssertionError: expected 'Retrievin...formation:27017' to equal 'localhost:27018'
      + expected - actual
      -Retrievin...formation:27017
      +localhost:27018
https://travis-ci.com/10gen/compass/jobs/71220024

  1) #explain when running queries on the explain plan "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) #explain "after all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  https://travis-ci.com/10gen/compass/jobs/71221451https://travis-ci.com/10gen/compass/jobs/71221451

  1) #collections "before all" hook:
     element (title=MongoDB Compass - localhost:27018) still not existing after 13000ms
https://travis-ci.com/10gen/compass/jobs/71227535

  1) #explain when running queries on the explain plan "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) #explain "after all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71227537

  1) #connect "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) #explain "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  3) #indexes "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  4) #query-bar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  5) #schema "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  6) #sidebar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71228171

  1) #indexes "before all" hook:
     Error: An element could not be located on the page using the given search parameters ("input[name=hostname]").
https://travis-ci.com/10gen/compass/jobs/71228166