Revert "Merge pull request #294 from 10gen/INT-1091-migrations"
This reverts commit 394e8d7a2cc8e8208fee513e04bd19a15556f32a, reversing
changes made to 2c64e35b2cf2836a0c0e8cd4f18a21370b3577d6.

Reverting due to "Uncaught Error: Cannot find module './features'" in app