COMPASS-944 Part 2: Charts Refactoring (#942)
* Refactor: Move getFieldPanelItemTitles from click to get

* Update misleading test context from crud to charts

* Decouple CustomToggle from DraggableField

Also resolves an eslint warning.

* Apply the more specific eslint-disable-line syntax

http://stackoverflow.com/questions/27732209/turning-off-eslint-rule-for-a-specific-line

* Refactor: Use an example item constant, as in the docs

http://react-dnd.github.io/react-dnd/docs-overview.html

Note: This for some reason returns `null` when in the Chrome/Electron debugger, but works fine otherwise!

* Remove unused import

#retry
  1) SchemaStore shares a "null" schema as JSON #race "before each" hook for "copies to the clipboard":
     TypeError: Cannot read property 'handleSchemaShare' of undefined
https://travis-ci.com/10gen/compass/jobs/72771819

  1) #databases when creating & deleting databases reduces the database count:
      AssertionError: expected '1' to equal '0'
      + expected - actual
      -1
      +0
https://travis-ci.com/10gen/compass/jobs/72771820

  1) #databases when creating & deleting databases reduces the database count:
      AssertionError: expected '2' to equal '0'
      + expected - actual
      -2
      +0
https://travis-ci.com/10gen/compass/jobs/72771508

  1) #data-service when using data-service directly "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/72771509

  1) #schema when applying a filter in the schema tab checks the collections table:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/72771510