Test refactor: DRY field and type requires
Note: In this file you can already see enzyme tests with the tooltip data exist in the same pattern as was expected from COMPASS 904:
https://github.com/10gen/compass/pull/904/files#diff-141ece4d9c46a6395999a8d5653c2803

#retry
'#query-bar when using advanced query options when using the fanclub collection with 100 docs goes to the index tab and creates an index'
https://travis-ci.com/10gen/compass/jobs/71072503

  1) #query-bar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71073705

  1) #sidebar "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71074834

  1) #connect when connecting to a server when the server exists renders the home screen:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
https://travis-ci.com/10gen/compass/jobs/71074835

  1) #launch when launching the application displays the feature tour modal:
     Error: element ([data-test-id='feature-tour-modal']) still not visible after 13000ms
https://travis-ci.com/10gen/compass/jobs/71074831

  1) #explain "before all" hook:
     element (title=MongoDB Compass - localhost:27018) still not existing after 13000ms
https://travis-ci.com/10gen/compass/jobs/71074832