Hack: Move main/renderer process tests from `test` dir into `tests` dir
So “Zoom renderer tests” do not fail:
  Zoom renderer tests
    3) should zoom reset
    4) "after each" hook for "should zoom reset"
…
  3) Zoom renderer tests should zoom reset:
     TypeError: Cannot read property 'setZoomLevel' of undefined
      at zoomReset (src/app/menu-renderer.js:10:10)
      at Context.it (test/renderer-process/zoom.test.js:9:12)

  4) Zoom renderer tests "after each" hook for "should zoom reset":
     TypeError: Cannot read property 'setZoomLevel' of undefined
      at zoomReset (src/app/menu-renderer.js:10:10)
      at Context.afterEach (test/renderer-process/zoom.test.js:6:5)

Also hadron-build does not support the notion of separate testing processes, just a combined one, so we’ll want to revisit this later when we can agree what should go where.