COMPASS-3116: Only electron-rebuild keytar and kerberos
[hadron-compile-cache](https://github.com/mongodb-js/hadron-compile-cache) :arrow_right: depends on chokidar :arrow_right: depends on fsevents...

http://npm.im/fsevents is supposed to be macOS only but there is something super wacky going on with that project... and because `electron-rebuild` doesn't unstead that `fsevents` is a transitive optional dependency of `hadron-compile-cache` (a real production dependency), `electron-rebuild` throws a panic and dies because `fsevents` (macOS only) cannot be rebuilt on Windows (which is not macOS). :dizzy_face:

```
An unhandled error occurred inside electron-rebuild
Traceback (most recent call last):
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\data\\mci\\a4c1d1b6e5075de7c6e444eac5bab731\\src\\.deps\\node.exe" "Z:\\data\\mci\\a4c1d1b6e5075de7c6e444eac5bab731\\src\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.6" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=fse" "--module_path=Z:\\data\\mci\\a4c1d1b6e5075de7c6e444eac5bab731\\src\\node_modules\\fsevents\\lib\\binding\\Release\\electron-v3.0-win32-x64" "--remote_path=./v1.2.4/" "--package_name=fse-v1.2.4-electron-v3.0-win32-x64.tar.gz" "--host=https://fsevents-binaries.s3-us-west-2.amazonaws.com"
gyp ERR! cwd Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Failed with exit code: 1
```

An unhandled error occurred inside electron-rebuild
Traceback (most recent call last):
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\data\\mci\\a4c1d1b6e5075de7c6e444eac5bab731\\src\\.deps\\node.exe" "Z:\\data\\mci\\a4c1d1b6e5075de7c6e444eac5bab731\\src\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.6" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=fse" "--module_path=Z:\\data\\mci\\a4c1d1b6e5075de7c6e444eac5bab731\\src\\node_modules\\fsevents\\lib\\binding\\Release\\electron-v3.0-win32-x64" "--remote_path=./v1.2.4/" "--package_name=fse-v1.2.4-electron-v3.0-win32-x64.tar.gz" "--host=https://fsevents-binaries.s3-us-west-2.amazonaws.com"
gyp ERR! cwd Z:\data\mci\a4c1d1b6e5075de7c6e444eac5bab731\src\node_modules\fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Failed with exit code: 1